// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_hxto07YPviJocdVK3TB5YFRSk7HrHcE',
    appId: '1:714946331695:web:96bc2b920acbf6724e32da',
    messagingSenderId: '714946331695',
    projectId: 'vhembe-gov',
    authDomain: 'vhembe-gov.firebaseapp.com',
    storageBucket: 'vhembe-gov.appspot.com',
    measurementId: 'G-RE0EHBETKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCowu1dUAG1RQT9etTsLrgahtBe3m-m5F8',
    appId: '1:714946331695:android:ca2a8d58e4db7d1d4e32da',
    messagingSenderId: '714946331695',
    projectId: 'vhembe-gov',
    storageBucket: 'vhembe-gov.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNIla8nBV5g8Raz_Cc9Q9ST5-vZycvJjg',
    appId: '1:714946331695:ios:def305f7aef4d59b4e32da',
    messagingSenderId: '714946331695',
    projectId: 'vhembe-gov',
    storageBucket: 'vhembe-gov.appspot.com',
    iosClientId: '714946331695-kpvqk61ulfrv799gqact9gjn9o34lk7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.vhembeGov',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNIla8nBV5g8Raz_Cc9Q9ST5-vZycvJjg',
    appId: '1:714946331695:ios:def305f7aef4d59b4e32da',
    messagingSenderId: '714946331695',
    projectId: 'vhembe-gov',
    storageBucket: 'vhembe-gov.appspot.com',
    iosClientId: '714946331695-kpvqk61ulfrv799gqact9gjn9o34lk7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.vhembeGov',
  );
}
